name: time-series-methods
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # Core data manipulation and scientific computing
  - pandas
  - numpy
  # Visualization
  - matplotlib
  - seaborn
  # Machine learning
  - scikit-learn
  # Time series analysis
  - statsmodels
  - scipy
  # Notebook environment
  - jupyter
  - ipykernel
  - pip
  - pip:
    # ML models
    - tabpfn-client
    - tabpfn-time-series
    - autogluon.timeseries
    # Time series tools
    - sktime
    - ruptures
    # Utilities
    - python-dotenv